title: Login.gov Partners

collections:
  pages:
    output: true
    permalink: /:path/

kramdown:
  hard_wrap: true

defaults:
  - scope:
      path: ''
    values:
      layout: page

copy_to_destination:
  - node_modules/identity-style-guide/dist/assets
